/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/households/{household_id}/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Plans */
        get: operations["list_plans_households__household_id__plans_get"];
        put?: never;
        /** Create Plan */
        post: operations["create_plan_households__household_id__plans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/households/{household_id}/plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Plan */
        get: operations["get_plan_households__household_id__plans__plan_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/households/{household_id}/plans/{plan_id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Plan */
        post: operations["validate_plan_households__household_id__plans__plan_id__validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/households/{household_id}/plans/{plan_id}/propose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Propose Plan */
        post: operations["propose_plan_households__household_id__plans__plan_id__propose_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/households/{household_id}/plans/{plan_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Plan */
        post: operations["approve_plan_households__household_id__plans__plan_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/households/{household_id}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Transactions
         * @description List transactions for the household. Filter by month (YYYY-MM) or pocket.
         */
        get: operations["list_transactions_households__household_id__transactions_get"];
        put?: never;
        /** Create Transaction */
        post: operations["create_transaction_households__household_id__transactions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/households/{household_id}/transactions/{tx_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Transaction */
        get: operations["get_transaction_households__household_id__transactions__tx_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Transaction */
        patch: operations["update_transaction_households__household_id__transactions__tx_id__patch"];
        trace?: never;
    };
    "/households/{household_id}/comparison/{month}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Comparison
         * @description Plan vs actual deviation for the given month (YYYY-MM). Core: API-1.5/1.6.
         */
        get: operations["get_comparison_households__household_id__comparison__month__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/households/{household_id}/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulate Expense
         * @description Check if a proposed expense is feasible: green / amber / red + trade-off. Core: API-2.1.
         */
        post: operations["simulate_expense_households__household_id__simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/households/{household_id}/debts/avalanche": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Avalanche
         * @description Return debts ordered by avalanche strategy (highest rate first). Core: API-1.6.
         */
        get: operations["get_avalanche_households__household_id__debts_avalanche_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/households/{household_id}/leisure/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Leisure Status
         * @description Current leisure budget consumption: available, spent, caps. Core: API-2.2.
         */
        get: operations["get_leisure_status_households__household_id__leisure_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/households/{household_id}/close-month": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Close Month Endpoint
         * @description Archive the active plan, generate monthly report, and surface alerts. API-2.12/2.13.
         */
        post: operations["close_month_endpoint_households__household_id__close_month_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/households/{household_id}/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Alerts
         * @description Generate proactive budget alerts for the household for the current (or given) month. API-2.10.
         */
        get: operations["get_alerts_households__household_id__alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description Conversational agent: narrates, simulates, explains — never computes money. API-1.15.
         */
        post: operations["chat_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Alert */
        Alert: {
            /** Alert Id */
            alert_id: string;
            /** Household Id */
            household_id: string;
            /**
             * Type
             * @description overspend | near_cap | unmatched_tx | low_ef
             */
            type: string;
            severity: components["schemas"]["AlertSeverity"];
            /** Message */
            message: string;
            /** Pocket Id */
            pocket_id?: string | null;
            /** Month */
            month?: string | null;
        };
        /**
         * AlertSeverity
         * @enum {string}
         */
        AlertSeverity: "red" | "amber" | "info";
        /** ApprovalRequest */
        ApprovalRequest: {
            /** Uid */
            uid: string;
            /** Approved */
            approved: boolean;
        };
        /** AvalancheEntry */
        AvalancheEntry: {
            /** Debt Id */
            debt_id: string;
            /** Creditor */
            creditor: string;
            /** Balance */
            balance: string;
            currency: components["schemas"]["Currency"];
            /** Rate */
            rate: string;
            /** Payment */
            payment: string;
            /** Priority */
            priority: number;
            /** Months To Payoff */
            months_to_payoff?: number | null;
        };
        /** AvalancheResponse */
        AvalancheResponse: {
            /** Household Id */
            household_id: string;
            /** Debts */
            debts: components["schemas"]["AvalancheEntry"][];
            /**
             * Total Balance Usd
             * @description All balances converted to USD
             */
            total_balance_usd: string;
        };
        /** ChatMessage */
        ChatMessage: {
            /**
             * Role
             * @description 'user' or 'assistant'
             */
            role: string;
            /** Content */
            content: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Household Id */
            household_id: string;
            /** Messages */
            messages: components["schemas"]["ChatMessage"][];
            /**
             * Stream
             * @default false
             */
            stream: boolean;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Reply */
            reply: string;
            /** Tool Calls Made */
            tool_calls_made?: string[];
        };
        /** CloseMonthResponse */
        CloseMonthResponse: {
            /** Household Id */
            household_id: string;
            /** Month */
            month: string;
            /** Archived Plan Id */
            archived_plan_id?: string | null;
            /** Alert Count */
            alert_count: number;
            /** Alerts */
            alerts: components["schemas"]["Alert"][];
            /** Total Planned */
            total_planned: string;
            /** Total Actual */
            total_actual: string;
            /** Total Delta */
            total_delta: string;
        };
        /** ComparisonResponse */
        ComparisonResponse: {
            /**
             * Month
             * @description YYYY-MM
             */
            month: string;
            /** Household Id */
            household_id: string;
            /** Items */
            items: components["schemas"]["DeviationItem"][];
            /** Total Planned */
            total_planned: string;
            /** Total Actual */
            total_actual: string;
            /** Total Delta */
            total_delta: string;
        };
        /**
         * Currency
         * @enum {string}
         */
        Currency: "CRC" | "USD";
        /** DeviationItem */
        DeviationItem: {
            /** Pocket Id */
            pocket_id: string;
            /** Pocket Name */
            pocket_name: string;
            currency: components["schemas"]["Currency"];
            /** Planned */
            planned: string;
            /** Actual */
            actual: string;
            /** Delta */
            delta: string;
            /** Delta Pct */
            delta_pct?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** LeisureStatus */
        LeisureStatus: {
            /** Household Id */
            household_id: string;
            /**
             * Period Start
             * Format: date
             */
            period_start: string;
            /**
             * Period End
             * Format: date
             */
            period_end: string;
            /** Individual */
            individual: {
                [key: string]: unknown;
            }[];
            /** Household Budget */
            household_budget?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * LineType
         * @enum {string}
         */
        LineType: "income" | "expense" | "debt" | "leisure" | "transfer";
        /** Plan */
        Plan: {
            /** Id */
            id: string;
            /** Household Id */
            household_id: string;
            /**
             * Version
             * @default 1
             */
            version: number;
            status: components["schemas"]["PlanStatus"];
            /**
             * Period
             * @description {"from": date, "to": date}
             */
            period: {
                [key: string]: string;
            };
            /**
             * Approvals
             * @description uid → bool; all True = proposed → active
             */
            approvals?: {
                [key: string]: boolean;
            };
            /** Lines */
            lines?: components["schemas"]["PlanLine"][];
        };
        /** PlanCreate */
        PlanCreate: {
            /**
             * Period From
             * Format: date
             */
            period_from: string;
            /**
             * Period To
             * Format: date
             */
            period_to: string;
            /** Lines */
            lines: components["schemas"]["PlanLineCreate"][];
        };
        /** PlanLine */
        PlanLine: {
            /** Id */
            id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Pocket Id */
            pocket_id: string;
            /** Concept */
            concept: string;
            /** Amount */
            amount: string;
            currency: components["schemas"]["Currency"];
            /** Category */
            category: string;
            type: components["schemas"]["LineType"];
        };
        /** PlanLineCreate */
        PlanLineCreate: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Pocket Id */
            pocket_id: string;
            /** Concept */
            concept: string;
            /** Amount */
            amount: number | string;
            currency: components["schemas"]["Currency"];
            /**
             * Category
             * @default general
             */
            category: string;
            type: components["schemas"]["LineType"];
        };
        /**
         * PlanStatus
         * @enum {string}
         */
        PlanStatus: "draft" | "proposed" | "active" | "archived";
        /** PlanValidateResponse */
        PlanValidateResponse: {
            /** Valid */
            valid: boolean;
            /** Errors */
            errors?: string[];
            /** Warnings */
            warnings?: string[];
        };
        /**
         * SimulateRequest
         * @description Propose an out-of-plan expense; core returns traffic-light + trade-off.
         */
        SimulateRequest: {
            /** Pocket Id */
            pocket_id: string;
            /** Amount */
            amount: number | string;
            currency: components["schemas"]["Currency"];
            /** Concept */
            concept: string;
            /**
             * Proposed Date
             * Format: date
             */
            proposed_date: string;
            /**
             * Fx
             * @description Override FX rate for conversion
             */
            fx?: number | string | null;
        };
        /** SimulateResponse */
        SimulateResponse: {
            light: components["schemas"]["TrafficLight"];
            /** Feasible */
            feasible: boolean;
            /**
             * Sacrifice
             * @description What gets deferred or reduced to fund this expense
             */
            sacrifice?: string | null;
            /**
             * Source
             * @description Which pocket/line absorbs the expense
             */
            source?: string | null;
            /**
             * Detail
             * @description Human-readable explanation (narrated by the agent)
             */
            detail: string;
        };
        /**
         * TrafficLight
         * @enum {string}
         */
        TrafficLight: "green" | "amber" | "red";
        /** Transaction */
        Transaction: {
            /** Id */
            id: string;
            /** Household Id */
            household_id: string;
            /** Pocket Id */
            pocket_id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Concept */
            concept: string;
            /** Amount */
            amount: string;
            currency: components["schemas"]["Currency"];
            /**
             * Fx
             * @description Exchange rate at time of transaction
             */
            fx?: string | null;
            /** Plan Line Id */
            plan_line_id?: string | null;
            status: components["schemas"]["TxStatus"];
            /** Category */
            category: string;
            /** Split */
            split?: components["schemas"]["TxSplit-Output"][];
            /** Created At */
            created_at?: string | null;
        };
        /** TransactionCreate */
        TransactionCreate: {
            /** Pocket Id */
            pocket_id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Concept */
            concept: string;
            /** Amount */
            amount: number | string;
            currency: components["schemas"]["Currency"];
            /** Fx */
            fx?: number | string | null;
            /** Plan Line Id */
            plan_line_id?: string | null;
            /**
             * Category
             * @default general
             */
            category: string;
            /** Split */
            split?: components["schemas"]["TxSplit-Input"][];
        };
        /** TransactionUpdate */
        TransactionUpdate: {
            /** Plan Line Id */
            plan_line_id?: string | null;
            /** Category */
            category?: string | null;
            /** Split */
            split?: components["schemas"]["TxSplit-Input"][] | null;
        };
        /** TxSplit */
        "TxSplit-Input": {
            /** Uid */
            uid: string;
            /** Amount */
            amount: number | string;
        };
        /** TxSplit */
        "TxSplit-Output": {
            /** Uid */
            uid: string;
            /** Amount */
            amount: string;
        };
        /**
         * TxStatus
         * @enum {string}
         */
        TxStatus: "in_plan" | "out_of_plan";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_plans_households__household_id__plans_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                household_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_plan_households__household_id__plans_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                household_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plan_households__household_id__plans__plan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                household_id: string;
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_plan_households__household_id__plans__plan_id__validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                household_id: string;
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanValidateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    propose_plan_households__household_id__plans__plan_id__propose_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                household_id: string;
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_plan_households__household_id__plans__plan_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                household_id: string;
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_transactions_households__household_id__transactions_get: {
        parameters: {
            query?: {
                month?: string | null;
                pocket_id?: string | null;
            };
            header?: never;
            path: {
                household_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_transaction_households__household_id__transactions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                household_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_transaction_households__household_id__transactions__tx_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                household_id: string;
                tx_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_transaction_households__household_id__transactions__tx_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                household_id: string;
                tx_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_comparison_households__household_id__comparison__month__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                household_id: string;
                month: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparisonResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_expense_households__household_id__simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                household_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_avalanche_households__household_id__debts_avalanche_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                household_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvalancheResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_leisure_status_households__household_id__leisure_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                household_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeisureStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_month_endpoint_households__household_id__close_month_post: {
        parameters: {
            query?: {
                month?: string | null;
            };
            header?: never;
            path: {
                household_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloseMonthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_alerts_households__household_id__alerts_get: {
        parameters: {
            query?: {
                month?: string | null;
            };
            header?: never;
            path: {
                household_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
